version: '3.8'
services:
  main:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: eventdrivenwithlaravel
    volumes:
      - .:/app
    ports:
        - 8001:8000
    depends_on:
        - main_db
  main_db:
    image: mysql:8.0.25
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306
